version: '2'

services:

  db-backup:
    container_name: db-backup
    build: .
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASS=
    volumes:
      - .:/opt/mysql/backup
